Base:
  model_root: ./checkpoints/
  num_workers: 3
  verbose: 1
  early_stop_patience: 2
  pickle_feature_encoder: true
  save_best_only: true
  eval_steps: null
  debug_mode: false
  group_id: null
  use_features: null
  feature_specs: null
  feature_config: null
RankMixer_movielenslatest_x1_unified:
  loss: binary_crossentropy
  task: binary_classification
  optimizer: adam
  learning_rate: 0.001
  embedding_regularizer: 0
  net_regularizer: 0
  epochs: 100
  shuffle: true
  seed: 2024
  monitor_mode: max
  early_stop_patience: 2
  dataset_id: movielenslatest_x1
  batch_size: 4096
  metrics:
  - AUC
  - logloss
  monitor: AUC
  model: RankMixer
  embedding_dim: 40
  num_transformer_layers: 2
  transformer_dropout: 0.1
  ffn_dim: 80
  use_pos_embedding: true
  output_mlp_hidden_units:
  - 80
  - 40
  net_dropout: 0.1
  batch_norm: false
RankMixer_frappe_x1_unified:
  loss: binary_crossentropy
  task: binary_classification
  optimizer: adam
  learning_rate: 0.001
  embedding_regularizer: 0
  net_regularizer: 0
  epochs: 100
  shuffle: true
  seed: 2024
  monitor_mode: max
  early_stop_patience: 2
  dataset_id: frappe_x1
  batch_size: 4096
  metrics:
  - AUC
  - logloss
  monitor: AUC
  model: RankMixer
  embedding_dim: 56
  num_transformer_layers: 2
  transformer_dropout: 0.1
  ffn_dim: 112
  use_pos_embedding: true
  output_mlp_hidden_units:
  - 112
  - 56
  net_dropout: 0.1
  batch_norm: false
RankMixer_kuaivideo_x1_unified:
  loss: binary_crossentropy
  task: binary_classification
  optimizer: adam
  learning_rate: 0.001
  embedding_regularizer: 0
  net_regularizer: 0
  epochs: 100
  shuffle: true
  seed: 2024
  monitor_mode: max
  early_stop_patience: 2
  dataset_id: kuaivideo_x1
  batch_size: 8192
  metrics:
  - gAUC
  - AUC
  - logloss
  monitor:
    AUC: 1
    gAUC: 1
  model: RankMixer
  group_id: group_id
  embedding_dim: 40
  num_transformer_layers: 2
  transformer_dropout: 0.1
  ffn_dim: 80
  use_pos_embedding: true
  output_mlp_hidden_units:
  - 80
  - 40
  net_dropout: 0.1
  batch_norm: false
RankMixer_taobaoad_x1_unified:
  loss: binary_crossentropy
  task: binary_classification
  optimizer: adam
  learning_rate: 0.001
  embedding_regularizer: 0
  net_regularizer: 0
  epochs: 100
  shuffle: true
  seed: 2024
  monitor_mode: max
  early_stop_patience: 2
  dataset_id: taobaoad_x1
  batch_size: 8192
  metrics:
  - gAUC
  - AUC
  - logloss
  monitor:
    AUC: 1
    gAUC: 1
  model: RankMixer
  group_id: group_id
  embedding_dim: 48
  num_transformer_layers: 2
  transformer_dropout: 0.1
  ffn_dim: 96
  use_pos_embedding: true
  output_mlp_hidden_units:
  - 96
  - 48
  net_dropout: 0.1
  batch_norm: false
