movielenslatest_x1:
  data_format: csv
  data_root: /home/raoxuan/projects/open_unimixer_skills/data
  feature_cols:
    - active: true
      dtype: str
      name: user_id
      type: categorical
    - active: true
      dtype: str
      name: item_id
      type: categorical
    - active: true
      dtype: str
      name: tag_id
      type: categorical
  label_col:
    dtype: float
    name: label
  min_categr_count: 1
  test_data: /home/raoxuan/projects/open_unimixer_skills/data/MovielensLatest_x1/test.csv
  train_data: /home/raoxuan/projects/open_unimixer_skills/data/MovielensLatest_x1/train.csv
  valid_data: /home/raoxuan/projects/open_unimixer_skills/data/MovielensLatest_x1/valid.csv
frappe_x1:
  data_format: csv
  data_root: /home/raoxuan/projects/open_unimixer_skills/data
  feature_cols:
    - active: true
      dtype: str
      name: user
      type: categorical
    - active: true
      dtype: str
      name: item
      type: categorical
    - active: true
      dtype: str
      name: daytime
      type: categorical
    - active: true
      dtype: str
      name: weekday
      type: categorical
    - active: true
      dtype: str
      name: isweekend
      type: categorical
    - active: true
      dtype: str
      name: homework
      type: categorical
    - active: true
      dtype: str
      name: cost
      type: categorical
    - active: true
      dtype: str
      name: weather
      type: categorical
    - active: true
      dtype: str
      name: country
      type: categorical
    - active: true
      dtype: str
      name: city
      type: categorical
  label_col:
    dtype: float
    name: label
  min_categr_count: 1
  test_data: /home/raoxuan/projects/open_unimixer_skills/data/Frappe_x1/test.csv
  train_data: /home/raoxuan/projects/open_unimixer_skills/data/Frappe_x1/train.csv
  valid_data: /home/raoxuan/projects/open_unimixer_skills/data/Frappe_x1/valid.csv
kuaivideo_x1:
  data_format: csv
  data_root: /home/raoxuan/projects/open_unimixer_skills/data
  feature_cols:
    - active: true
      dtype: int
      name: group_id
      preprocess: copy_from(user_id)
      remap: false
      type: meta
    - active: true
      dtype: str
      name: user_id
      type: categorical
    - active: true
      dtype: str
      name: item_id
      type: categorical
    - active: true
      dtype: str
      embedding_dim: 64
      min_categr_count: 1
      name: item_emb
      preprocess: copy_from(item_id)
      pretrained_emb: 
        /home/raoxuan/projects/open_unimixer_skills/data/KuaiShou/KuaiVideo_x1/item_visual_emb_dim64.h5
      type: categorical
    - active: true
      dtype: str
      max_len: 100
      name: pos_items
      padding: pre
      share_embedding: item_id
      splitter: ^
      type: sequence
    - active: true
      dtype: str
      max_len: 100
      name: neg_items
      padding: pre
      share_embedding: item_id
      splitter: ^
      type: sequence
    - active: true
      dtype: str
      embedding_dim: 64
      max_len: 100
      min_categr_count: 1
      name: pos_items_emb
      padding: pre
      preprocess: copy_from(pos_items)
      pretrained_emb: 
        /home/raoxuan/projects/open_unimixer_skills/data/KuaiShou/KuaiVideo_x1/item_visual_emb_dim64.h5
      share_embedding: item_emb
      splitter: ^
      type: sequence
    - active: true
      dtype: str
      embedding_dim: 64
      max_len: 100
      min_categr_count: 1
      name: neg_items_emb
      padding: pre
      preprocess: copy_from(neg_items)
      pretrained_emb: 
        /home/raoxuan/projects/open_unimixer_skills/data/KuaiShou/KuaiVideo_x1/item_visual_emb_dim64.h5
      share_embedding: item_emb
      splitter: ^
      type: sequence
  label_col:
    dtype: float
    name: is_click
  min_categr_count: 10
  test_data: /home/raoxuan/projects/open_unimixer_skills/data/KuaiShou/KuaiVideo_x1/test.csv
  train_data: /home/raoxuan/projects/open_unimixer_skills/data/KuaiShou/KuaiVideo_x1/train.csv
  valid_data: /home/raoxuan/projects/open_unimixer_skills/data/KuaiShou/KuaiVideo_x1/test.csv
  feature_specs:
    - feature_encoder: nn.Linear(64, 64, bias=False)
      name: item_emb
    - feature_encoder: layers.MaskedAveragePooling()
      name: pos_items
    - feature_encoder: layers.MaskedAveragePooling()
      name: neg_items
    - feature_encoder:
        - layers.MaskedAveragePooling()
        - nn.Linear(64, 64, bias=False)
      name: pos_items_emb
    - feature_encoder:
        - layers.MaskedAveragePooling()
        - nn.Linear(64, 64, bias=False)
      name: neg_items_emb
taobaoad_x1:
  data_format: csv
  data_root: /home/raoxuan/projects/open_unimixer_skills/data
  feature_cols:
    - active: true
      dtype: int
      name: group_id
      preprocess: copy_from(userid)
      remap: false
      type: meta
    - active: true
      dtype: str
      name:
        - userid
        - cms_segid
        - cms_group_id
        - final_gender_code
        - age_level
        - pvalue_level
        - shopping_level
        - occupation
        - new_user_class_level
        - adgroup_id
        - cate_id
        - campaign_id
        - customer
        - brand
        - pid
        - btag
      type: categorical
    - active: true
      dtype: float
      name: price
      type: numeric
    - active: true
      dtype: str
      max_len: 50
      name: cate_his
      padding: pre
      share_embedding: cate_id
      splitter: ^
      type: sequence
    - active: true
      dtype: str
      max_len: 50
      name: brand_his
      padding: pre
      share_embedding: brand
      splitter: ^
      type: sequence
    - active: true
      dtype: str
      max_len: 50
      name: btag_his
      padding: pre
      share_embedding: btag
      splitter: ^
      type: sequence
  label_col:
    dtype: float
    name: clk
  min_categr_count: 10
  test_data: /home/raoxuan/projects/open_unimixer_skills/data/TaobaoAd_x1/test.csv
  train_data: /home/raoxuan/projects/open_unimixer_skills/data/TaobaoAd_x1/train.csv
  valid_data: /home/raoxuan/projects/open_unimixer_skills/data/TaobaoAd_x1/test.csv
microvideo1.7m_x1:
  data_format: csv
  data_root: /home/raoxuan/projects/open_unimixer_skills/data
  feature_cols:
    - active: true
      dtype: int
      name: group_id
      preprocess: copy_from(user_id)
      remap: false
      type: meta
    - active: true
      dtype: str
      name: user_id
      type: categorical
    - active: true
      dtype: str
      embedding_dim: 64
      name: item_id
      pretrained_emb: 
        /home/raoxuan/projects/open_unimixer_skills/data/MicroVideo1.7M_x1/item_image_emb_dim64.h5
      type: categorical
    - active: true
      dtype: str
      name: cate_id
      type: categorical
    - active: true
      dtype: str
      embedding_dim: 64
      max_len: 100
      name: clicked_items
      padding: pre
      pretrained_emb: 
        /home/raoxuan/projects/open_unimixer_skills/data/MicroVideo1.7M_x1/item_image_emb_dim64.h5
      splitter: ^
      type: sequence
    - active: true
      dtype: str
      max_len: 100
      name: clicked_categories
      padding: pre
      share_embedding: cate_id
      splitter: ^
      type: sequence
    - active: false
      dtype: str
      name: timestamp
      type: categorical
  label_col:
    dtype: float
    name: is_click
  min_categr_count: 1
  test_data: /home/raoxuan/projects/open_unimixer_skills/data/MicroVideo1.7M_x1/test.csv
  train_data: /home/raoxuan/projects/open_unimixer_skills/data/MicroVideo1.7M_x1/train.csv
  valid_data: /home/raoxuan/projects/open_unimixer_skills/data/MicroVideo1.7M_x1/test.csv
